### ISSUE TITLE
single node yaml runs into an error connecting to zookeeper

### ISSUE THREAD

**Issue by caleb15** [tableau/tableau-server-in-kubernetes#10]
When deploying the single node yaml onto EKS 1.21 with latest version of Tableau server and Tableau docker image setup repo I get an error when initializing the topology. The node has 8CPU and 32GB memory, which I imagine should be enough to at least start Tableau.

```
tail -n 20 /var/opt/tableau/tableau_server/supervisord/run-tableau-server.log
42% - Waiting for services to reconfigure.    
Running - Initializing the topology.
An error occurred retrieving job status. The job may still be running, but TSM could not retrieve its status. You may be able to check the job status using the 'tsm jobs list' or 'tsm jobs reconnect' commands.
+ delete_files_on_exit
+ '[' 0 -gt 0 ']'
```

```
[tableau@tableau-0 /]$ tsm jobs reconnect --id 1
Reconnecting to asynchronous job...
2% - Checking control plane services.
5% - Validating that there are no pending changes.
7% - Generating new asset key.
10% - Saving asset key.
12% - Generating passwords.
15% - Generating secret keys.
17% - Generating apigateway mutual SSL certificates.
20% - Generating Apache Gateway Internal mutual SSL certificates.
22% - Generating Unique Cluster Identifier.
25% - Generating Search Server SSL certificate.
27% - Generating Index And Search Server SSL certificate.
30% - Generating ActiveMQ Server SSL certificate.
32% - Generating internal Metadata API mutual SSL certificates.
35% - Generating key store.
37% - Generating Hyper SSL certificate.
40% - Promoting configuration.
42% - Waiting for services to reconfigure.
Running - Initializing the topology.
Job id is '1', timeout is 150 minutes.

Server initialization was unsuccessful.
This job failed due to unexpected error: '{0}'
```

If "{0}'" could be replaced with a more descriptive error that would be great. Anyways, continuing on:

In `/var/opt/tableau/tableau_server/data/tabsvc/logs/tabadmincontroller/tabadmincontroller_node1-0.log` I saw 

```
2022-05-12 02:29:23.331 +0000  pool-20-thread-1 : ERROR com.tableausoftware.tabadmin.webapp.asyncjobs.JobStepRunner - Running step InitializeTopology failed
```
and
```
2022-05-12 02:42:21.787 +0000  main-SendThread(tableau-0:8976) : INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server tableau-0/10.10.43.33:8976. Will not attempt to authenticate using SASL (unknown error)
2022-05-12 02:42:21.856 +0000  nioEventLoopGroup-4-1 : INFO  org.apache.zookeeper.ClientCnxnSocketNetty - SSL handler added for channel: [id: 0x5047ef5d]
2022-05-12 02:42:21.864 +0000  nioEventLoopGroup-4-1 : INFO  org.apache.zookeeper.ClientCnxnSocketNetty - future isn't success, cause:
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: tableau-0/10.10.43.33:8976
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.73.Final.jar:4.1.73.Final]
        at java.lang.Thread.run(Unknown Source) [?:?]

```
Note the "Will not attempt to authenticate using SASL (unknown error)" message. Not sure if that's of concern.

Zookeeper status says active. There is a error listed, may or may not be source of issue? I have not made any modifications to zookeeper.
```
[tableau@tableau-0 /]$ /var/opt/tableau/tableau_server/data/tabsvc/services/appzookeeper_0.20221.22.0415.1144/appzookeeper/appzookeeper status
[584] [INFO] 2022-05-12 17:58:22.233 +0000 : Loading configuration from /var/opt/tableau/tableau_server/data/tabsvc/services/appzookeeper_0.20221.22.0415.1144/appzookeeper/appzookeeper.runjavaservice.json
[584] [INFO] 2022-05-12 17:58:22.234 +0000 : Loading configuration from /var/opt/tableau/tableau_server/data/tabsvc/services/appzookeeper_0.20221.22.0415.1144/config/appzookeeper.runjavaservice.json
[584] [INFO] 2022-05-12 17:58:22.234 +0000 : Loading manifest from /var/opt/tableau/tableau_server/data/tabsvc/services/appzookeeper_0.20221.22.0415.1144/appzookeeper/appzookeeper.jar
[584] [INFO] 2022-05-12 17:58:22.234 +0000 : Starting malloc_trim thread. Run every 60 sec. Heap pad MB: 1
[584] [INFO] 2022-05-12 17:58:22.239 +0000 : Loading JVM library /var/opt/tableau/tableau_server/data/tabsvc/services/appzookeeper_0.20221.22.0415.1144/repository/jre/lib/server/libjvm.so
[584] [INFO] 2022-05-12 17:58:22.513 +0000 : Java class name: com.tableausoftware.zookeeper.Zookeeper; Method name: main; Arguments: status
	ERROR org.apache.zookeeper.server.quorum.QuorumPeerConfig - Invalid configuration, only one server specified (ignoring)
{
  "currentDeploymentState" : "NONE",
  "details" : {
    "code" : "imok"
  },
  "name" : "appzookeeper_0",
  "processStatus" : "ACTIVE",
  "timestampUtc" : 1652378307447,
  "version" : "20221.22.0415.1144"
}
```

Here's our /etc/hosts file:
```
[tableau@tableau-0 /]$ cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.10.43.33	tableau-0
```

**Comment by caleb15** [comment]
It looks like the issue was that Tableau takes an extremely long time to startup, so the livenessprobe restarts it before it can finish initializing. The initialDelaySeconds should be increased to - unfortunately I didn't time it exactly - something like a half hour if I remember right.

**Comment by caleb15** [comment]
Ideally a startupProbe would be used here. Unfortunately when I tested the startupProbe for some reason the livenessProbe started running before the startupProbe completed :/

**Comment by caleb15** [comment]
I should also mention 8 CPU & 32 gigs is not enough, you need _at least_ 16 CPU and 64 gigs to even start Tableau.
