### ISSUE TITLE
three-node setup, pgsql (repository) does not survive restart if the ip of the pod changes

### ISSUE THREAD

**Issue by olevchyk** [tableau/tableau-server-in-kubernetes#11]
tableau version: tableau-server-20214.22.0420.0834-20214-22.0420.0834.x86_64 official docker image 

We have been experimenting with 3 statefulset pods  setup, the installation went smooth and we got it up and running, with active passive local pgsql (repository)  running on primary and one of the worker nodes accordingly. 
The problem appeared when we tried to reboot any of the pods which has pgsql role, so when pod is up and running, in case the ip changes some services like pgsql  never recovered. 
I've tried different conditions: 
1. just reboot the pod, - issue occurs
2. tsm stop, and then reboot the pod, - the same issue 
3. tsm topology failover-repository and then reboot the passive pod - the same issue. 

some exceptions from the logs: 
/var/opt/tableau/tableau_server/data/tabsvc/logs/pgsql/spawn.log 
```
pg_basebackup: error: FATAL:  no pg_hba.conf entry for replication connection from host "10.xx.xx.xx", user "tblwgadmin", SSL on
FATAL:  no pg_hba.conf entry for replication connection from host "10.xx.xx.xx", user "tblwgadmin", SSL off
```
/var/opt/tableau/tableau_server/data/tabsvc/logs/vizqlserver/vizqlserver_node1-0.log
```
NativeApiLifecycleThread : ERROR wgsessionId= com.tableausoftware.resource.maps.GlobalGeocodingInfoProvider - Exception while reading geocoding paths
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:467) ~[spring-orm-5.3.18.jar:5.3.18]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400) ~[spring-tx-5.3.18.jar:5.3.18]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-5.3.18.jar:5.3.18]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:595) ~[spring-tx-5.3.18.jar:5.3.18]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:382) ~[spring-tx-5.3.18.jar:5.3.18]
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:71) ~[spring-aspects-5.3.18.jar:5.3.18]
	at com.tableausoftware.resource.maps.dao.GlobalGeocodingDaoJpa.getAllActiveEntries(GlobalGeocodingDaoJpa.java:80) ~[tab-resource-maps-latest.jar:?]
	at com.tableausoftware.resource.maps.GeocodingInfoService.getAllActiveEntries_aroundBody14(GeocodingInfoService.java:133) ~[tab-resource-maps-latest.jar:?]
	at com.tableausoftware.resource.maps.GeocodingInfoService$AjcClosure15.run(GeocodingInfoService.java:1) ~[tab-resource-maps-latest.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167) ~[aspectjrt-1.9.5.jar:?]
	at com.tableausoftware.aspects.search.TransactionLoggerAspect.trackLongRunningTransaction(TransactionLoggerAspect.java:71) ~[tab-domain-indexing-interfaces-latest.jar:?]
	at com.tableausoftware.resource.maps.GeocodingInfoService.getActiveGlobalEntries(GeocodingInfoService.java:133) ~[tab-resource-maps-latest.jar:?]
	at com.tableausoftware.resource.maps.GlobalGeocodingInfoProvider.getVersionedGeocodingPath(GlobalGeocodingInfoProvider.java:202) ~[tab-resource-maps-latest.jar:?]
	at com.tableausoftware.resource.maps.GlobalGeocodingInfoProvider.ensureCurrent(GlobalGeocodingInfoProvider.java:154) ~[tab-resource-maps-latest.jar:?]
	at com.tableausoftware.resource.maps.GlobalGeocodingInfoProvider.runPreInitHook(GlobalGeocodingInfoProvider.java:97) ~[tab-resource-maps-latest.jar:?]
	at com.tableausoftware.nativeapi.NativeApiManager.invokePreInitHooks(NativeApiManager.java:203) ~[tab-nativeapi-latest.jar:?]
	at com.tableausoftware.nativeapi.NativeApiManager.serverInit(NativeApiManager.java:208) ~[tab-nativeapi-latest.jar:?]
	at com.tableausoftware.nativeapi.NativeApiManager.lambda$start$0(NativeApiManager.java:355) ~[tab-nativeapi-latest.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionImpl.connection(SessionImpl.java:480) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:152) ~[spring-orm-5.3.18.jar:5.3.18]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.18.jar:5.3.18]
	... 22 more
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "10.xx.xx.xx", user "rails", database "workgroup", SSL on

``` 

Does this mean we need static internal ips to make it work properly? 
Is there any workaround for this except [rebuilding the cluster](https://kb.tableau.com/articles/howto/change-ip-addresses-of-computers-running-tableau-server?_ga=2.118533901.566653680.1656918696-1872131340.1650370507) ?  

What I also see that /var/opt/tableau/tableau_server/data/tabsvc/config/pgsql_0.20214.22.0420.0834/pg_hba.conf 
contains the outdated ips, maybe there is way to reload it alongside the other configs ?

**Comment by olevchyk** [comment]
The answer to this question I found partially at https://kb.tableau.com/articles/issue/identifying-and-disabling-temporary-ipv6-addresses?_ga=2.12511152.566653680.1656918696-1872131340.1650370507 in the issue definition 

"Tableau Server requires static IPv4 or IPv6 addresses. You may notice undesirable symptoms if your cluster has temporary IPv6 addresses (which are dynamic) enabled." 

Would be nice to get a confirmation for this requirement , thanks in advance

**Comment by caleb15** [comment]
Not sure what the answer is but just to warn you, Tableau does not seem to be monitoring or maintaining this repo. As far as I can tell not a single issue here has had a response from Tableau. In addition opening a support case with Tableau does not guarantee a fix as Kubernetes has community level support.

**Comment by olevchyk** [comment]
thanks for the info, just to add a bit more context for the other users running into the same issue

- this is most likely not the issue for the setup with external repository but this [requires Server Management Addon](https://help.tableau.com/current/server/en-us/server_external_repo.htm)
- a hack that worked for us was to append a hard-coded sub-range of internal ips in /opt/tableau/tableau_server/packages/templates.${SERVICE_VERSION}/pg_hba.conf.ftl 

Another alternative is a runtime replacement of the current ip inside pg_hba.conf, let's say from a custom entry-point  or by patching CMD (start-process-manager) , but I found this hard to maintain and error prone on multi-node setup , because if replica fails, primary should be also aware of new ip and vice versa.
