### ISSUE TITLE
Failing to install/configure Tabadmin Controller

### ISSUE THREAD

**Issue by FreebeJan** [tableau/tableau-server-in-kubernetes#3]
Hi I am facing an issue when initializing tableau on kubernetes:

```
2022-01-28 14:26:22.523 +0000 205 main : DEBUG com.tableausoftware.tabadmin.configuration.builder.AppConfigurationBuilder - Writing connections properties /var/opt/tableau/tableau_server/data/tabsvc/services/connections.properties
2022-01-28 14:26:22.524 +0000 205 main : DEBUG com.tableausoftware.tabadmin.configuration.builder.AppConfigurationBuilder - Picking connection settings from dataengine over vizqlserver.
2022-01-28 14:26:22.537 +0000 205 main : ERROR com.tableausoftware.tabadmin.webapp.TabadminController - Exception while configuring process.
java.nio.file.FileSystemException: /var/opt/tableau/tableau_server/data/tabsvc/services/connections.properties: Operation not supported
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.LinuxDosFileAttributeView.readAttributes(LinuxDosFileAttributeView.java:182) ~[?:?]
	at com.tableausoftware.files.PropertiesFile.cloneSecurity(PropertiesFile.java:83) ~[file-utils-20214.0.10.jar:?]
	at com.tableausoftware.files.PropertiesFile.storeSorted(PropertiesFile.java:118) ~[file-utils-20214.0.10.jar:?]
	at com.tableausoftware.tabadmin.configuration.builder.AppConfigurationBuilder.writeConnectionProperties(AppConfigurationBuilder.java:486) ~[tab-tabadmin-config-latest.jar:?]
	at com.tableausoftware.tabadmin.configuration.builder.AppConfigurationBuilder.writeConfigurationFiles(AppConfigurationBuilder.java:635) ~[tab-tabadmin-config-latest.jar:?]
	at com.tableausoftware.tabadmin.configuration.builder.AppConfigurationBuilder.build(AppConfigurationBuilder.java:328) ~[tab-tabadmin-config-latest.jar:?]
	at com.tableausoftware.tabadmin.configuration.builder.AppConfigurationBuilder.buildAndWriteConfigurations(AppConfigurationBuilder.java:104) ~[tab-tabadmin-config-latest.jar:?]
	at com.tableausoftware.service.control.BaseTableauServiceCommands.buildAndWriteWorkgroupConfig(BaseTableauServiceCommands.java:359) ~[control-shared-latest.jar:?]
	at com.tableausoftware.service.control.BaseTableauServiceCommands.generateLocalConfigs(BaseTableauServiceCommands.java:315) ~[control-shared-latest.jar:?]
	at com.tableausoftware.tabadmin.webapp.TabadminController$Commands.configureImpl(TabadminController.java:299) [control-tabadmincontroller.jar:?]
	at com.tableausoftware.tabadmin.webapp.TabadminController$Commands.install(TabadminController.java:446) [control-tabadmincontroller.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.tableausoftware.commandline.SwitchCommand$1.run(SwitchCommand.java:174) [tab-commandline-jewel-cli-latest.jar:?]
	at com.tableausoftware.commandline.SimpleCommand.execute(SimpleCommand.java:47) [tab-commandline-jewel-cli-latest.jar:?]
	at com.tableausoftware.commandline.SwitchCommand.execute(SwitchCommand.java:129) [tab-commandline-jewel-cli-latest.jar:?]
	at com.tableausoftware.tabadmin.webapp.TabadminController.main(TabadminController.java:171) [control-tabadmincontroller.jar:?]
```
Do you have any idea what might be causing this?

**Comment by FreebeJan** [comment]
We pinpointed the problem to be related to using an EFS volume mount. If we remove the persistent volume everything works without issue. We really need to persist the files though. Do you have a recommendation as to how we should persist /var/opt/tableau with EKS on AWS?

**Comment by kavyatappa** [comment]
@FreebeJan 

Can you send me your multi node yaml file for reference and understand more on the issue?

**Comment by FreebeJan** [comment]
The issue was solved by moving to ebs

**Comment by caleb15** [comment]
Same issue with EFS and the latest version of tableau server (2022.1.1). @FreebeJan are you running multi-node? Because as I understand it EBS can only be bound to one node at a time, so using EBS would rule out multi-node deployments. Yet we need multi-node for HA.

@nbrandes-tableau not sure if you are the right person to contact but there's a bunch of issues in this repo without responses, it would be nice to some eyes on this.

**Comment by zikphil** [comment]
> Same issue with EFS and the latest version of tableau server (2022.1.1). @FreebeJan are you running multi-node? Because as I understand it EBS can only be bound to one node at a time, so using EBS would rule out multi-node deployments. Yet we need multi-node for HA.
> 
> @nbrandes-tableau not sure if you are the right person to contact but there's a bunch of issues in this repo without responses, it would be nice to some eyes on this.

Did you ever figure it out?
